[package]
name = "event"
version = "0.1.0"
alya-version = "0.0.19"
entry = "src/lib.alya"
description = "High-concurrency reactor event loop, timers, and I/O multiplexer for Alya"
authors = ["Alya Language Contributors <https://github.com/alya-lang>"]
license = "MIT"
homepage = "https://github.com/alya-lang/alya"
repository = "https://github.com/alya-lang/event"
keywords = ["alya", "alya-lang", "package", "event", "event-loop", "reactor", "concurrency", "networking", "timers"]

[dependencies]
uv = { git = "https://github.com/alya-lang/uv", tag = "v0.1.0" }

# [lint]
# disabled_rules = []
# exclude = []
